# Generated by Django 3.2.1 on 2021-06-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210603_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='imageFileName',
            field=models.CharField(default='file.jpg', max_length=200),
        ),
    ]
